FROM arm64v8/python:3.14

EXPOSE 80

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./main.py /code

CMD ["fastapi", "run", "main.py", "--port", "80"]
